Add mlknn
deeppavlov/AutoIntent pull request #11
Opened 2024-09-29 16:34 UTC by Samoed

2024-09-30 11:24 UTC, voorhs commented on tests/test_modules/test_scoring/test_mlknn.py
> +        mode="multiclass",
Странно, что "multiclass", если это multilabel knn

2024-09-30 12:47 UTC, Samoed commented on tests/test_modules/test_scoring/test_mlknn.py
> +        predictions == np.array([[1.0, 1.0,], [1.0, 1.0,], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]])
```suggestion
        predictions == np.array([[1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0], [1.0, 1.0]])
```

2024-09-30 22:34 UTC, Samoed commented
Я забыл запушить свои изменения

2024-09-30 23:20 UTC, voorhs commented
Кроме мультилейбл ты даешь на вход мультикласс данные, но из-за того что стоял режим `multilabel`, эти данные просто игнорились (эта логика прописана в конструкторе DataHandler)

Чтобы мультикласс данные не игнорились, надо ставить `multiclass_as_multilabel`. Сейчас я поставил этот режим и теперь `test_mlknn.py` падает.

Пересмотришь этот тест?

2024-09-30 23:23 UTC, voorhs requested changes

2024-09-30 23:23 UTC, voorhs commented on tests/test_modules/test_scoring/test_mlknn.py
> +    np.testing.assert_almost_equal(0.75, scorer.score(context, scoring_f1))
вот это место

2024-09-30 23:23 UTC, voorhs commented on tests/test_modules/test_scoring/test_mlknn.py
> +    assert (predictions == np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])).all()
и вот это

2024-10-01 07:45 UTC, Samoed commented on tests/test_modules/test_scoring/test_mlknn.py
> +    data = load_data("../../minimal-optimization/data/clinc_subset.json", multilabel=False)
```suggestion
    data = load_data("tests/minimal-optimization/data/clinc_subset.json", multilabel=False)
```

2024-10-01 10:10 UTC, voorhs approved these changes

2024-10-01 10:13 UTC, merged