Remove chroma
deeppavlov/AutoIntent pull request #16
Opened 2024-10-13 16:48 UTC by Samoed

2024-10-13 18:34 UTC, Samoed commented
Сейчас тесты не проходят из-за того что DNNC не передает конвертер и я не знаю стоит ли делать его опциональным. Также не знаю как лучше сделать возврат документов, которые требуются для него

2024-10-14 11:31 UTC, voorhs requested changes

2024-10-14 11:31 UTC, voorhs commented on autointent/context/vector_index.py
> +        all_results = [self.search_by_query(query, k) for query in queries]
Кажется, это неэффективная реализация, поскольку эмбедить и осуществлять поиск лучше батчами, а не по одному элементу

2024-10-14 11:31 UTC, voorhs commented on autointent/context/vector_index.py
> +    def query(
здесь в аргументы метода `VectorIndex.query()` можно не включать `converter`, а в вызов `index.query()`  передавать `converter=self.metadata_as_labels`

2024-10-14 11:31 UTC, voorhs commented on autointent/modules/scoring/knn/knn.py
> +        labels, distances = self._collection.query(utterances, self.k, self._converter)
и здесь, соответственно, не придется передавать `self._converter`

2024-10-14 11:31 UTC, voorhs commented on autointent/modules/scoring/linear.py
> +        labels = context.vector_index.metadata_as_labels(collection.get_metadata())
вот эту логику по конвертации было бы здорово перенести в класс VectorIndex, оформить в виде метода 
`get_all_labels`

2024-10-14 11:31 UTC, voorhs commented on autointent/modules/scoring/mlknn/mlknn.py
> +        self.labels = np.array(self._converter(dataset))
здесь логика с конвертацией тоже будет пропущена благодаря методу `VectorIndex.get_all_labels()`

2024-10-14 11:31 UTC, voorhs commented on autointent/modules/scoring/mlknn/mlknn.py
> +            neighbors = self.collection.search_by_embedding(self.features[i], self.k)
Мне кажется, тут тоже эффективнее будет избегать поиска по одному элементу. Лучше посчитать всех соседей заранее и батчами

2024-10-14 21:08 UTC, voorhs approved these changes

2024-10-14 21:12 UTC, merged