Add new dataset format
deeppavlov/AutoIntent pull request #17
Opened 2024-10-15 13:45 UTC by EgSergeenko

2024-10-16 11:31 UTC, voorhs requested changes

2024-10-16 11:31 UTC, voorhs commented on autointent/context/data_handler/schemas.py
> +        return DatasetType.multilabel
проверка на multiclass верная, но тут по-моему баг: если хотя бы один лейбл подан как список а все остальные как инты, то функция возвращает `DatasetType.multilabel`, хотя должна возвращать ошибку мол файл поломанный

2024-10-16 11:31 UTC, voorhs commented on autointent/context/data_handler/multilabel_generation.py
>          raise FileNotFoundError(msg)
вот этой проверки быть не должно, потому что config_string это уже какой-то json объект, а не путь к нему

не ты эту проверку добавил, видимо я проглядел в предыдущих PR

2024-10-16 11:31 UTC, voorhs commented on autointent/context/data_handler/data_handler.py
> -            old_utterances = convert_to_multilabel_format(multiclass_intent_records)
вот эту логику по конвертации мультикласс датасета в мультилейбл датасет, хотелось бы сохранить, она очень удобная при тестировании, потому что один и тот же json файл можно подавать для теста и мультиклассовых и мультилейбловых модулей

мб добавить опциональный параметр в конструктор?

2024-10-16 11:31 UTC, voorhs commented on autointent/context/data_handler/stratification.py
>          in_domain_mask = np.array(labels) != -1
то, как здесь обрабатываются OOS примеры, немного противоречит полю `Utterance.oos` из файла `schemas.py`

2024-10-16 11:31 UTC, voorhs commented on autointent/context/data_handler/stratification.py
> +        n_classes = len(classes) if -1 not in classes else len(classes) - 1
и здесь противоречит `Utterance.oos`

2024-10-16 11:31 UTC, voorhs commented on autointent/context/data_handler/stratification.py
> +            if utterance.oos:
кажется вот здесь должно вылезти противоречие в обработке OOS

2024-10-16 11:39 UTC, EgSergeenko commented on autointent/context/data_handler/schemas.py
> +        return DatasetType.multilabel
Согласен. Все проверки на валидность датасета планировал сделать в дальнейшем.

2024-10-16 11:40 UTC, EgSergeenko commented on autointent/context/data_handler/stratification.py
> +        n_classes = len(classes) if -1 not in classes else len(classes) - 1
Выяснили, что здесь все окей.

2024-10-17 14:02 UTC, EgSergeenko commented on autointent/context/data_handler/stratification.py
>          in_domain_mask = np.array(labels) != -1
Пофиксил

2024-10-17 14:31 UTC, EgSergeenko commented on autointent/context/data_handler/data_handler.py
> -            old_utterances = convert_to_multilabel_format(multiclass_intent_records)
Вернул эту возможность. В тестах пока оставлю оба файла в разных форматах. Переделаю после этого реквеста #20

2024-10-17 15:19 UTC, voorhs approved these changes

2024-10-17 15:32 UTC, merged