Feat/inference configs
deeppavlov/AutoIntent pull request #21
Opened 2024-10-17 14:43 UTC by voorhs

Python API & CLI для инференса

2024-10-17 16:40 UTC, Samoed requested changes

2024-10-17 16:40 UTC, Samoed commented on autointent/context/vector_index_client/vector_index.py
> +        with (self.dump_dir / "texts.txt").open("w") as file:
Мб в один файл писать тексты и лейблы и сделать его json?

2024-10-17 16:40 UTC, Samoed commented on autointent/context/vector_index_client/vector_index.py
> +        self.embedding_model.save(str(self.dump_dir / "embedding_model"))
Эмбеддер не обучается, мб не стоит его сохранять?

2024-10-17 16:40 UTC, Samoed commented on autointent/context/vector_index_client/vector_index.py
>          return self.embedding_model.encode(utterances, convert_to_numpy=True)
Добавь сюда проверку тоже проверку модели на None

2024-10-17 16:40 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
> +        path = self.db_dir / "indexes_dirnames.json"
Если все что в файле хранится это путь до папки с индексами, и у нас название папки это модель, то мб как-то можно избавиться от файла?

2024-10-17 16:40 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
> +        indexes_dirnames[model_name] = dir_name
Просто название модели так лучше не использовать на прямую. Тк если там будет записан полный путь к модели, то дампить будет странно + непереносимость между OC

2024-10-17 16:40 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
> +        path = self.db_dir / "indexes_dirnames.json"
Мб в metadata перенести?

2024-10-17 16:40 UTC, Samoed commented on autointent/modules/prediction/threshold.py
> +        with (dump_dir / "metadata.json").open() as file:
Мб в переменную базового класса вынести?

2024-10-17 16:40 UTC, Samoed commented on autointent/modules/retrieval/vectordb.py
> +        with (dump_dir / "vector_index_client_kwargs.json").open() as file:
Тоже в meta

2024-10-17 16:40 UTC, Samoed commented on autointent/modules/scoring/knn/knn.py
> +        self.metadata = {
Мб для metadata структуру отдельную какую-нибудь придумать?

2024-10-17 16:40 UTC, Samoed commented on autointent/pipeline/inference/cli_endpoint.py
Мб все что связано с cli в отдельную папку?

2024-10-17 17:09 UTC, voorhs commented on autointent/context/vector_index_client/vector_index.py
> +        self.embedding_model.save(str(self.dump_dir / "embedding_model"))
в будущем будет обучаться)

2024-10-21 08:12 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
> +        path = self.db_dir / "indexes_dirnames.json"
не, этот словарик-файл я как раз создал потому что название папки не точно совпадает с названием модели

2024-10-21 08:14 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
> +        indexes_dirnames[model_name] = dir_name
пока что укажем, что не поддерживаются локальные модели, а только из репозиториев hugging face

2024-10-21 08:16 UTC, voorhs commented on autointent/modules/prediction/threshold.py
> +        with (dump_dir / "metadata.json").open() as file:
не, и вот почему:
- метадата у каждого модуля своя
- для каких-то модулей вообще не нужна
- метадаты между модулями никак не связаны
- метадата используется исключительно для дампинга и загрузки модуля

2024-10-21 08:17 UTC, voorhs commented on autointent/pipeline/inference/cli_endpoint.py
пока что для инференса и оптимизации пусть все будет по отдельности

2024-10-21 10:07 UTC, Samoed commented on autointent/modules/prediction/threshold.py
> +        with (dump_dir / "metadata.json").open() as file:
Я про само название `metadata.json`, тк это часто у тебя встречается

2024-10-21 10:08 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
> +        indexes_dirnames[model_name] = dir_name
Все равно надо заменить `/` в названии

2024-10-21 10:36 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
> +        indexes_dirnames[model_name] = dir_name
этот словарик-файл как раз реализует отображение имени со слешем в filesystem-compatible имя без слеша

2024-10-21 10:39 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
> +        indexes_dirnames[model_name] = dir_name
Увидел

2024-10-21 10:41 UTC, Samoed commented on autointent/modules/prediction/threshold.py
> +        with (dump_dir / "metadata.json").open() as file:
Но и для каждого класса потом можно свой класс для метадаты сделать (хотя бы как typeddict)

2024-10-21 13:09 UTC, Samoed approved these changes

2024-10-21 15:26 UTC, merged