add_logit_adaptivness
deeppavlov/AutoIntent pull request #23
Opened 2024-10-18 06:47 UTC by JakeRaskind

2024-10-30 15:50 UTC, Samoed commented on autointent/modules/prediction/logit_adaptivness.py
> +def _detect_oos(classes: np.array[int], scores: np.array[float], threshes: np.array[float]) -> np.array:
Надо как 
``python
import numpy.typing as npt

def _detect_oos(classes: npt.NDArray[np.int64], scores: npt.NDArray[np.float32], threshes: npt.NDArray[np.float32]) -> npt.NDArray[np.int64]:
```

2024-11-02 13:51 UTC, voorhs reviewed
Надо разобраться `axis=0` или все таки `axis=1`. Мне кажется правильным второй вариант. Если это так, то надо переписать `_detect_oos()`

Еще ты не прогнал форматтер по коду, это нужно сделать. Команда `make lint` в терминале

2024-11-02 13:51 UTC, voorhs commented on autointent/modules/__init__.py
> +    LogitAdaptivnessPredictor,
давай назовем AdaptivePredictor? так короче

2024-11-02 13:51 UTC, voorhs commented on autointent/modules/__init__.py
> +    "logit_adapt": LogitAdaptivnessPredictor
здесь соответственно `"adaptive"`

2024-11-02 13:51 UTC, voorhs commented on autointent/modules/prediction/logit_adaptivness.py
соответственно этот файл назовем `adaptive.py`

2024-11-02 13:51 UTC, voorhs commented on autointent/modules/prediction/logit_adaptivness.py
> +    return r * np.max(scores, axis=0) + (1 - r) * np.min(scores, axis=0) # type: ignore[no-any-return]
а здесь разве не должно быть `axis=1`? просто получается что ты смотришь на максимум и минимум не у конкретного семпла (вероятности внутри строки) а у всего набора для данного класса

2024-11-02 13:51 UTC, voorhs commented on autointent/modules/prediction/logit_adaptivness.py
> +    return classes
вот это как будто не соотносится с тем как я представлял себе этот метод

тут ты для каждого класса свой трешхолд считаешь, а надо же чтобы у каждого объекта был один трешхолд на все классы?

или у меня глюки?

2024-11-05 15:00 UTC, JakeRaskind commented
названия поменял. Теперь касательно осей и смысла метода. Я помедитировал на статью ещё раз и, соглашусь, в статье имелось в виду скалирование скоров по сэмплу, а не по классу. В связи с этим там adaptive поменялся весьма радикально (как оказалось, jinoos_adapter - это худший темплейт для adaptive_predictor)

2024-11-06 08:07 UTC, voorhs requested changes

2024-11-06 08:07 UTC, voorhs commented on autointent/modules/prediction/adaptive.py
> +    return res
здесь еще не исправлена логика с `axis=0`

2024-11-19 13:19 UTC, voorhs approved these changes

2024-11-19 13:19 UTC, merged