Fixing CUDA OOM
deeppavlov/AutoIntent pull request #26
Opened 2024-10-22 20:31 UTC by Dmitryv-2024

Проблема была в дефолтном batch_size=32 SentenceTransformer
Для вычисления эмбедингов либа добивала предложения паддингом до самого большого в батче. Это увеличивает требования по памяти и время инференса. По умолчанию, размер батча теперь 1. Но можно сменить в конфиге параметром embedder_batch_size.

2024-10-22 20:35 UTC, Dmitryv-2024 commented
Я завтра поправлю ворнинги и тесты.

2024-10-22 20:42 UTC, voorhs approved these changes

2024-10-22 20:42 UTC, voorhs commented on autointent/modules/scoring/linear.py
> +        # del self._embedder
Тогда, мне кажется, стоит удалить сам индекс. Есть метод `VectorIndex.delete()`

2024-10-22 21:19 UTC, Samoed commented
Проблема не только в batch_size, надо сделать так, чтобы можно было еще и длину зафиксировать, тк у разных моделей она разная и не всегда будет целиком полезна

2024-10-22 21:32 UTC, voorhs commented
> Проблема не только в batch_size, надо сделать так, чтобы можно было еще и длину зафиксировать, тк у разных моделей она разная и не всегда будет целиком полезна

Разве sentence transformers не сам выбирает как раз ту длину которая нужна модельке? Там 512, 1024 и проч

2024-10-22 21:35 UTC, Samoed commented
Да, сам выбирает и ставит максимальную. Поэтому когда ты использовал bge-m3 у тебя длина была 8192 и все вылетало по памяти, хотя 512 помещалось

2024-10-22 21:42 UTC, voorhs commented
> Да, сам выбирает и ставит максимальную. Поэтому когда ты использовал bge-m3 у тебя длина была 8192 и все вылетало по памяти, хотя 512 помещалось как я описал в [#22 (comment)](https://github.com/deeppavlov/AutoIntent/issues/22#issuecomment-2420258844)

Хмм но ведь он по идее должен ставить 8192 только если действительно есть текст не меньшей длины

2024-10-22 21:45 UTC, Samoed commented
Он просто будет всегда ставить 8192 и не будет смотреть на длину

2024-10-22 22:00 UTC, voorhs commented
> Он просто будет всегда ставить 8192 и не будет смотреть на длину

Тогда надо вот этот параметр тоже протянуть до конфига, чтобы пользователь выбрал longest или max_length, по умолчанию мне кажется стоит сделать longest

2024-10-22 22:56 UTC, Samoed requested changes

2024-10-22 22:56 UTC, Samoed commented on autointent/configs/optimization_cli.py
> +    embedder_batch_size: int = 1
Я бы не стал делать по дефолту batch_size 1, лучше оставить 32 и дать его регулировать

2024-10-23 15:51 UTC, Dmitryv-2024 commented on autointent/configs/optimization_cli.py
> +    embedder_batch_size: int = 1
Так мы и даем его регулировать. Вот так в коммандной строке: autointent embedder_batch_size=10 .....

FYI: На моей GPU с 4Гб, c дефолтным значением batch_size=32 на eurlex-20shot.json оптимизация у меня шла 60 мин. С batch_size=2 20 мин, с batch_size=1 ~ 8мин. Значительное ускорение получилось. 
Дополнительно на большом batch_size, CUDA ядра большую часть времени простаивали, при малом размере batch_size загрузка равномерная до 100%.

2024-10-23 16:03 UTC, Dmitryv-2024 commented
Можете кинуть ссылку в доках где про max_tokens говорится? не смог найти

2024-10-23 16:38 UTC, Samoed commented
Он почему-то странно сделал. В CrossEncoder можно напрямую это прокинуть, а в SentenceTransformer можно передать tokenizer_args и там их указать

2024-10-23 20:18 UTC, voorhs commented on autointent/configs/optimization_cli.py
> +    embedder_batch_size: int = 1
@Dmitryv-2024 Наверное рома согласен с тем что его надо позволить регулировать пользователю, но не согласен с дефолтным значением 1. Наверное потому что в общем случае (не для таких экстремально длинных текстов) прогон текстов через эмбедер батчами эффективнее.

Как только исправишь все ошибки надо замерить время оптимизации в зависимости от размера батча на других датасетах и удостовериться в этом. Это могу сделать я, если ты хочешь перейти к следующим задачками

2024-10-24 12:20 UTC, voorhs commented
> Можете кинуть ссылку в доках где про max_tokens говорится? не смог найти

https://www.sbert.net/docs/package_reference/sentence_transformer/models.html?highlight=pooling

2024-10-28 08:58 UTC, voorhs approved these changes

2024-10-28 14:30 UTC, merged