Feat/simpler fitting
deeppavlov/AutoIntent pull request #27
Opened 2024-10-22 21:18 UTC by Samoed

2024-10-24 19:49 UTC, Samoed commented on autointent/modules/prediction/base.py
>          oos_labels = [[0] * context.n_classes] * len(oos_scores) if context.multilabel else [-1] * len(oos_scores)  # type: ignore[list-item]
@voorhs Я попытался избавиться в scoring от context, но мне мешает эта функция, тк я не хочу уж слишком много параметров передавать

2024-10-25 08:08 UTC, voorhs requested changes

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/prediction/argmax.py
> +        if self.has_oos_samples:
мне кажется что этот ворнинг об oos_samples не так важен) можно не изголяться и избавиться от него

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/base.py
>          """
мне кажется метод score можно оставить с объектом контекста, потому что этот метод в принципе необходим только для оптимизации

в него обычно заложена сложная логика по извлечению данных с предыдущих узлов оптимизации, реализовать которую без объекта контекста даже не представляю как

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/prediction/base.py
>          oos_labels = [[0] * context.n_classes] * len(oos_scores) if context.multilabel else [-1] * len(oos_scores)  # type: ignore[list-item]
в одном из комментов написал, что Module.score можно оставить с объектом контекста

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/prediction/argmax.py
> +        if self.has_oos_samples:
по хорошему надо это инферить из данных: если в labels есть хотя бы одна oos метка (нулевой вектор / интежер -1) то выводить предупреждение

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/prediction/jinoos.py
> +        self.best_oos_scores = best_oos_scores
кажется эти best_oos_scores нигде не используются

плюс по-моему это идеологически неверно что мы передаем в конструктор данные для обучения

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/prediction/threshold.py
> +        self.has_oos_samples = has_oos_samples
эти три атрибута можно инферить из labels внутри метода fit, в конструктор их выносить мне кажется не нужно

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/base.py
> +    def from_context(cls, context: Context, **kwargs: dict[str, Any]) -> Self:
а почему не просто `-> "Module"`?

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/regexp.py
regexp можно пока в целом не трогать, в нем кучу другой работы надо сделать

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
> -    metadata_dict_name: str = "metadata.json"
эта строчка пропала, но атрибут ниже используется

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
в этом файле сильно набагано(

- `model_name` это кросс энкодер, а `biencoder_model` это `self.vector_index`
- потерялось сохрание `self.vector_index` в методе `fit`

P.S. векторный индекс надо доставать с помощью VectorIndexClient

2024-10-25 08:08 UTC, voorhs commented on autointent/modules/scoring/knn/knn.py
> +            multilabel=context.multilabel,
эти атрибуты можно инферить из данных в методе `fit`

2024-10-25 08:44 UTC, Samoed commented on autointent/modules/scoring/dnnc/dnnc.py
> -    metadata_dict_name: str = "metadata.json"
Я в базовый scoring перенес

2024-10-25 08:44 UTC, Samoed commented on autointent/modules/base.py
> +    def from_context(cls, context: Context, **kwargs: dict[str, Any]) -> Self:
Мне кажется, так более понятней и удобней

2024-10-25 08:45 UTC, Samoed commented on autointent/modules/prediction/base.py
>          oos_labels = [[0] * context.n_classes] * len(oos_scores) if context.multilabel else [-1] * len(oos_scores)  # type: ignore[list-item]
Тогда откачу коммит

2024-10-25 08:45 UTC, Samoed commented on autointent/modules/prediction/base.py
>          oos_labels = [[0] * context.n_classes] * len(oos_scores) if context.multilabel else [-1] * len(oos_scores)  # type: ignore[list-item]
Просто это странно немного

2024-10-25 08:52 UTC, voorhs commented on autointent/modules/prediction/base.py
>          oos_labels = [[0] * context.n_classes] * len(oos_scores) if context.multilabel else [-1] * len(oos_scores)  # type: ignore[list-item]
ну может быть в будущем и тут избавимся, а пока мне кажется можно обойтись

2024-10-25 10:15 UTC, Samoed commented on autointent/modules/prediction/threshold.py
> +        self.has_oos_samples = has_oos_samples
Да, но по сути это повторение того же кода, и можно не делать

2024-10-25 10:31 UTC, voorhs commented on autointent/modules/prediction/threshold.py
> +        self.has_oos_samples = has_oos_samples
с точки зрения user experience это неудобно

2024-10-25 11:04 UTC, voorhs requested changes

2024-10-25 11:04 UTC, voorhs commented on autointent/modules/retrieval/vectordb.py
> +        self.db_dir = context.db_dir
забыл убрать метод)

2024-10-25 11:04 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
> +        cross_encoder_name: str = "sentence-transformers/all-MiniLM-L6-v2",
кажется, что лучше `cross-encoder/ms-marco-MiniLM-L-6-v2`

2024-10-25 11:04 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
> +        vector_index.add(utterances, labels)
векторный индекс надо еще сохранить как атрибут, потому что он используется в методе `predict`

2024-10-25 11:04 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
> +        self.vector_index = vector_index_client.get_index(self.cross_encoder_name)
тут должно быть `self.search_model_name`

2024-10-25 14:01 UTC, Samoed commented
Что-то я не понимаю как vector index сохраняет данные и как их загрузить

2024-10-27 20:29 UTC, Samoed commented
Осталось дофиксить ThresholdOptimizer

2024-10-28 09:40 UTC, voorhs commented on autointent/context/optimization_info/optimization_info.py
> +        module_params: BaseMetadataDict,
вот это пока не понял зачем

2024-10-28 09:40 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
> +    def __init__(self, device: str, db_dir: str, **kwargs: dict[str, Any]) -> None:  # noqa: ARG002
а зачем здесь кварги?

2024-10-28 09:40 UTC, voorhs commented on autointent/modules/prediction/threshold.py
> +        )
тэги ведь тоже надо сохранять, они на в `predict()` используются

2024-10-28 09:40 UTC, voorhs commented on autointent/modules/prediction/jinoos.py
> +    ) -> None:
а зачем передавать трешхолд в конструктор? вроде это противоречит логике этого предиктора

2024-10-28 09:40 UTC, voorhs commented on autointent/modules/prediction/tunable.py
> +    ) -> None:
тут тоже непонятно зачем передавать трешхолд в конструктор

2024-10-28 09:40 UTC, voorhs commented on autointent/modules/retrieval/vectordb.py
> +        self.vector_index.dump(Path(self.db_dir))
тут `self.vector_index.dump()` не лишний? это же и так происходит в `VectorDBModule.dump()`

2024-10-28 09:40 UTC, voorhs commented on autointent/nodes/optimization/node_optimizer.py
>                      assets,  # retriever name / scores / predictions
по смыслу `module_kwargs` и `module.metadata` различаются

кварги - мл гиперпараметры

метадата - вспомогательная инфа для загрузки обученных весов

2024-10-28 09:40 UTC, voorhs commented on tests/modules/scoring/test_knn.py
мне кажется теперь можно убрать из этого теста часть с оптимизацией VectorDBModule, потому что раньше он нужен был чтобы создать векторный индекс, а теперь у нас он создается при вызове `KNNScorer.fit()`

2024-10-28 09:40 UTC, voorhs commented on tests/modules/scoring/test_linear.py
здесь тоже можно убрать часть с оптимизацией VectorDBModule

2024-10-28 09:40 UTC, voorhs commented on tests/modules/scoring/test_mlknn.py
и здесь

2024-10-28 09:48 UTC, Samoed commented on autointent/context/optimization_info/optimization_info.py
> +        module_params: BaseMetadataDict,
Я поменял, что модули теперь инициализируются не из диктов, а из метадаты

2024-10-28 09:48 UTC, Samoed commented on autointent/modules/prediction/threshold.py
> +        )
Да, это временная мера, тк там надо разобраться с dump/load

2024-10-28 09:51 UTC, Samoed commented on autointent/modules/retrieval/vectordb.py
> +        self.vector_index.dump(Path(self.db_dir))
Нет, у меня только так запустилось. В коде VectorDBModule сложно очень разобраться, чтобы все правильно дампилось

2024-10-30 08:00 UTC, voorhs commented on autointent/modules/scoring/linear.py
> +        features = vector_index.embedder.embed(utterances) if not vector_index.is_empty() else vector_index.get_all_embeddings()
тут главная цель этих строк была такая

1. избежать перерасчёта эмбедингов для всего датасета во время оптимизации
2. плюс надо было обеспечить чтобы на инференсе они все таки считались, если в векторном индексе их нету

по-моему сейчас пропала логика для пункта 1

2024-10-30 15:00 UTC, voorhs commented on autointent/configs/optimization_cli.py
> +    db_dir: Path = get_db_dir()  # noqa: RUF009
что-то мне нравится такое использование `get_db_dir()`, в этой функции есть логика по запоминанию папки кеша, эта функция вызывается в конструкторах разных модулей и `VectorIndexClient`

видимо для mypy сильно мешало значение None по умолчанию, да?

2024-10-30 15:00 UTC, voorhs commented on autointent/context/vector_index_client/vector_index.py
>              pass
какие-то странные строчки)

2024-10-30 15:00 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
> +        **kwargs: dict[str, Any],  # noqa: ARG002
а зачем тут кварги?

2024-10-30 15:00 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
>          return res
как будто этот метод теперь в любом случае создает индекс и заполняет его, теперь этот метод совсем не нужен и нужно всегда использовать `create_index()`

странное дело

2024-10-30 15:00 UTC, voorhs commented on autointent/modules/scoring/linear.py
ну вот тут точно делается лишняя работа и эмбединги пересчитываются)

исправлю это сам

2024-10-30 15:02 UTC, Samoed commented on autointent/context/vector_index_client/vector_index.py
>              pass
Это для тестов было

2024-10-30 15:02 UTC, Samoed commented on autointent/configs/optimization_cli.py
> +    db_dir: Path = get_db_dir()  # noqa: RUF009
Нет, просто у меня папка None создавалась

2024-10-30 15:03 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
>          return res
Для create_index нужны были utterances, labels. Раньше он просто падал, тк не хватало параметров

2024-10-30 15:04 UTC, Samoed commented on autointent/modules/scoring/linear.py
Нет, тут проблема в том что нам могут приходить другое количество эмбеддингов, не то что хранится в базе. У меня были какие-то проблемы из-за того что фичей было в 2 раза больше, чем label

2024-10-30 20:34 UTC, voorhs approved these changes

2024-10-31 08:31 UTC, Samoed commented on autointent/modules/scoring/description/description.py
> +        if isinstance(labels[0], list):
Может в отдельную функцию?

2024-10-31 08:34 UTC, Samoed commented on tests/pipeline/test_optimization.py
> +def get_config():
Давай не делать Callable фикстуры. Это очень неожиднно, тк обычно в фикстурах объекты, а такое можо просто как функцию оставить

2024-10-31 08:39 UTC, Samoed commented on tests/pipeline/test_optimization.py
> +def get_config():
(наверное потом отдельно буду менять)

2024-11-01 10:19 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +        if isinstance(labels[0], list):
а что именно нужно вынести в отдельную функцию? проверку типа лейбла?

2024-11-01 10:37 UTC, Samoed commented on autointent/modules/scoring/description/description.py
> +        if isinstance(labels[0], list):
Да

2024-11-01 12:08 UTC, truff4ut commented on autointent/context/context.py
> +        self.embedder_max_length = embedder_max_length
Потом надо будет задуматься над объединением параметров модели в один конфиг. Очень раздутый `__init__` по параметрам получается.

2024-11-01 12:08 UTC, truff4ut commented on autointent/context/embedder.py
По этому классу заметил, что загрузка модели по `model_name` и `model_path` происходит в разные моменты. Модель по `model_path` загружается в `__init__`, a по `model_name` уже непосредственно в методе `embed`. Если это ничем не обусловлено, то я бы загружал все в одном месте.

2024-11-01 12:08 UTC, truff4ut commented on autointent/context/vector_index_client/vector_index_client.py
> +from autointent.custom_types import LABEL_TYPE
Потом бы поменял на `LabelType` или просто `Label`.

2024-11-01 12:08 UTC, truff4ut commented on autointent/context/vector_index_client/vector_index_client.py
> +            res = self.get_index(model_name)
При вызове этого метода в консоли появится сообщение об ошибке. Хотя сам метод предполагает то, что индекса может не быть

2024-11-01 12:08 UTC, truff4ut commented on autointent/context/vector_index_client/vector_index_client.py
> +            res = self.get_index(model_name)
Возможно стоит немного поменять метод `get_index(...) -> VectorIndex | None`. И если запрашиваемого индекса нет, то обрабатывать это в функции, которая вызывает данный метод. Тогда можно будет убрать исключение из метода `get_index(...)` и каждый его вызов не придется оборачивать в `try: except:`

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/base.py
> +    def from_context(cls, context: Context, **kwargs: dict[str, Any]) -> Self:
Надо будет выбрать один вариант, потому что я где-то в этом проекте делал по-другому.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/base.py
>  class PredictionModule(Module, ABC):
Если `Module` наследуется от `ABC`, то это наследование в `PredictionModule` можно опустить.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/base.py
>          pass
Я бы использовал `...`, но это дело вкуса.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/base.py
>          pass
Но я бы точно делал везде одинаково. В некоторых абстрактных методах только докстринг без `pass`

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/base.py
> +    @overload  # type: ignore[misc]
`@overload` и исключение для него можно убрать

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/base.py
> +    def fit(
Плохо, что дочерний класс меняет сигнатуру метода. Надо подумать, что с этим можно сделать.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/base.py
Можно добавить какую-то логику, чтобы не прописывать `dump` и `load` в каждом классе. Можно будет развить эту идею и сделать так, чтобы не приходилось создавать класс метадаты для каждого модуля.

```python

import json
from pathlib import Path
from typing import Generic

import numpy as np
from numpy.typing import NDArray
from pydantic import BaseModel, field_serializer, field_validator
from typing_extensions import TypeVar


class BaseMetadata(BaseModel):
    class Config:
        arbitrary_types_allowed = True


T = TypeVar("T", bound=BaseMetadata)


class DumpMixin(Generic[T]):
    metadata: T

    def dump(self, path: Path) -> None:
        with (path / self.metadata_dict_name).open("w") as file:
            json.dump(self.metadata.model_dump(), file, indent=4)

    def load(self, path: Path) -> None:

        with (path / self.metadata_dict_name).open("r") as file:
            self.metadata = self.metadata.model_validate(json.load(file))

        for field in self.metadata.model_fields:
            setattr(self, field, getattr(self.metadata, field))


class JinoosPredictorMetadata(BaseMetadata):
    threshold: float


class JinoosPredictor(DumpMixin[JinoosPredictorMetadata]):
    metadata_dict_name: str = "jinoos.json"
    threshold: float

    def fit(self) -> None:
        self.threshold = 0.5
        self.metadata = JinoosPredictorMetadata(threshold=self.threshold)


class Tag(BaseModel):
    name: str
    intent_ids: list[int] = []


class ThresholdPredictorMetadata(BaseMetadata):
    multilabel: bool
    tags: list[Tag]
    threshold: float | NDArray[np.float64]
    n_classes: int

    @field_serializer("threshold")
    def serialize_threshold(
        self, threshold: float | NDArray[np.float64],
    ) -> float | list[float]:
        if isinstance(threshold, float):
            return threshold
        return threshold.tolist()

    @field_validator("threshold", mode="before")
    @classmethod
    def validate_threshold(
        cls, threshold: float | list[float],
    ) -> float | NDArray[np.float64]:
        if isinstance(threshold, float):
            return threshold
        return np.array(threshold)


class ThresholdPredictor(DumpMixin[ThresholdPredictorMetadata]):
    metadata_dict_name: str = "threshold.json"
    multilabel: bool
    tags: list[Tag]
    threshold: float | NDArray[np.float64]
    n_classes: int

    def fit(self) -> None:
        self.multilabel = True
        self.tags = [Tag(name="common", intent_ids=[0, 1])]
        self.threshold = np.array([0.1, 0.3])
        self.n_classes = 2
        self.metadata = ThresholdPredictorMetadata(
            multilabel=self.multilabel,
            tags=self.tags,
            threshold=self.threshold,
            n_classes=self.n_classes,
        )


if __name__ == "__main__":
    output_dir = Path("review")
    output_dir.mkdir(exist_ok=True)

    predictor = JinoosPredictor()
    predictor.fit()
    predictor.dump(output_dir)
    predictor.load(output_dir)

    predictor = ThresholdPredictor()
    predictor.fit()
    predictor.dump(output_dir)
    predictor.load(output_dir)
```

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/scoring/base.py
> +class ScoringModule(Module, ABC):
Аналогично про `ABC`

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/retrieval/vectordb.py
> +        self.metadata = VectorDBMetadata(
Если `metadata` всегда состоит только из полей класса и используется только для записи и чтения json, то стоит ли ее добавлять к полям модели?

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/base.py
Можем вместе посмотреть, как работает этот метод, и им вдохновиться

https://github.com/huggingface/transformers/blob/c2820c94916e34baf4486accae74760972183a2f/src/transformers/configuration_utils.py#L841

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/threshold.py
> +    tags: list[Tag] | None
Странно сохранять `tags`, `n_classes` в метаданные модулей. Мы же не сможем загрузить этот модуль с конкретными тегами и запустить его на других данных.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/scoring/description/description.py
>      def load(self, path: str) -> None:
Я бы разделил загрузку конфигов и весов во всех модулях. Загрузку конфигов довольно легко унифицировать, потому что это всегда +/- одинаковые словари. Веса для разных модулей загружаются по-разному (из того что я увидел).

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/prediction/threshold.py
> +    tags: list[Tag] | None
Можно сделать дамп контекста, в котором будет храниться общая информация по пайплайну, которая может использоваться в нескольких модулях.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/scoring/knn/knn.py
> +        if isinstance(labels[0], list):
Можно ли этот if вынести в метод `from_context`?

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/scoring/linear.py
> +            embedder = Embedder(self.device, self.model_name, batch_size=self.batch_size, max_length=self.max_length)
В `knn.py` создается векторный индекс для получения эмбеддингов, а тут напрямую класс `Embedder` вызывается

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/scoring/description/description.py
> +        if self.precomputed_embeddings:
Похожие if и логика работы с векторной базой во всех `fit` встречается у модулей `scoring`.

2024-11-01 12:08 UTC, truff4ut commented on autointent/modules/scoring/description/description.py
> +    def fit(
Было бы очень удобно, если бы этот метод принимал эмбеддинги. Логику по их получению надо вынести из метода `fit`.

2024-11-01 12:12 UTC, Samoed commented on autointent/modules/prediction/base.py
>  class PredictionModule(Module, ABC):
Нет, тк он не раализовывает все классы и не может быть вызван. Он является сам по себе абстрактным классом, поэтому тут должен быть abc

2024-11-01 12:12 UTC, voorhs commented on autointent/context/context.py
> +        self.embedder_max_length = embedder_max_length
Не очень понял. Про какие именно параметры говоришь?

2024-11-01 12:26 UTC, voorhs commented on autointent/modules/base.py
Мне кажется что мл-модули не стоит превращать в pydantic-модель, это как-то неожиданно для пользователя будет

Типа pydantic это же всегда про конфиги, а не про вычисляющие модули. Или я не шарю и есть примеры?

2024-11-01 12:28 UTC, Samoed commented on autointent/context/embedder.py
Вообще зачем тут `model_name` и `model_path`. Можно одно оставить

2024-11-01 12:30 UTC, voorhs commented on autointent/modules/prediction/base.py
> +    def fit(
Это очень сложно было избежать. Пока не представляю как исправить. 

Возможно в будущем нужно убрать общего предка Module, и чтобы отдельно были RetrievalModule, ScoringModule, PredictionModule

2024-11-01 12:32 UTC, voorhs commented on autointent/modules/prediction/threshold.py
> +    tags: list[Tag] | None
Тут не предполагается что будет использоваться на другом датасета. Поэтому теги с обучения будут актуальны

2024-11-01 12:32 UTC, Samoed commented on autointent/modules/base.py
LangChain на pydantic сделан, но не думаю, что это хороший пример, учитывая что мы меняем это для metadata только

2024-11-01 12:35 UTC, voorhs commented on autointent/modules/retrieval/vectordb.py
> +        self.metadata = VectorDBMetadata(
Вообще я согласен

@Samoed ты вкладывал какую-то особую логику когда делал metadata атрибутом? Или можно внести изменения про которые говорит Егор?

2024-11-01 12:40 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +        if self.precomputed_embeddings:
Дааа вот хороший вопрос как к этому относиться)

2024-11-01 12:42 UTC, Samoed commented on autointent/modules/scoring/description/description.py
> +            vector_index_client = VectorIndexClient(self.device, self.db_dir, self.batch_size, self.max_length)
А зачем тут пересоздание идет?

2024-11-01 12:47 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +    def fit(
Я пытался так сделать. Точно уже не помню почему, но это оказалось сложно реализуемой идеей.

Вся вот эта сложная логика по получению эмбедингов и векторных индексов нужна чтобы поддерживать сразу два случая: использование модуля с объектом контекста и без него

Может быть в будущем добавим поддержку эмбедингов на вход. Пока что я рад что эта логика хоть как-то реализована

2024-11-01 12:49 UTC, voorhs commented on autointent/modules/scoring/knn/knn.py
> +        if isinstance(labels[0], list):
Не, эта проверка должна быть и в случае когда мы оптимизируем без контекста

2024-11-01 12:50 UTC, voorhs commented on autointent/modules/scoring/linear.py
> +            embedder = Embedder(self.device, self.model_name, batch_size=self.batch_size, max_length=self.max_length)
В knn нужен именно сам индекс чтобы соседей искать, а тут не нужен

2024-11-01 12:52 UTC, voorhs reviewed
Оставил ревью чекпоинт для себя

2024-11-01 12:53 UTC, Samoed commented on autointent/modules/retrieval/vectordb.py
> +        self.metadata = VectorDBMetadata(
Она и до меня в полях была. Я только унифицировал

2024-11-01 12:56 UTC, Samoed commented on autointent/modules/retrieval/vectordb.py
> +        self.metadata = VectorDBMetadata(
Ты сделал так в https://github.com/deeppavlov/AutoIntent/pull/21, я продолжил

2024-11-01 13:04 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +            vector_index_client = VectorIndexClient(self.device, self.db_dir, self.batch_size, self.max_length)
Я щас с телефона, тут у гитхаба плохой интерфейс и я не могу пролистать файл вверх вниз, вижу только пару строк...

Но как могу догадаться это внутри метода fit. Там должен инициализироваться VectorIndexClient, а сам индекс должен доставаться методом get_index, он не предполагает пересоздание эмбедингов 

Надеюсь там внизу действительно get_index используется

2024-11-01 14:06 UTC, truff4ut commented on autointent/modules/prediction/base.py
>  class PredictionModule(Module, ABC):
```
from abc import ABC, abstractmethod


class Module(ABC):
    @abstractmethod
    def fit(self) -> None:
        ...


class PredictionModule(Module):
    @abstractmethod
    def fit(self) -> None:
        ...


module = PredictionModule()
```

2024-11-01 14:08 UTC, truff4ut commented on autointent/modules/prediction/base.py
> +    def fit(
Сделать в базовом классе `fit(*args, **kwargs)`

2024-11-01 14:09 UTC, truff4ut commented on autointent/modules/base.py
Давайте тогда думать, как это исправить. Сейчас все методы `load` и `dump` выглядят плохо

2024-11-01 14:10 UTC, truff4ut commented on autointent/modules/prediction/threshold.py
> +    tags: list[Tag] | None
Тогда надо из дампа датасета это загружать

2024-11-01 14:12 UTC, truff4ut commented on autointent/modules/scoring/description/description.py
> +        if self.precomputed_embeddings:
Класс любого модуля не должен в себе инкапсулировать логику по работе с векторной базой.

2024-11-01 14:14 UTC, truff4ut commented on autointent/modules/scoring/description/description.py
> +    def fit(
Зачем может понадобиться оптимизация без контекста?

2024-11-01 14:18 UTC, Samoed commented on autointent/context/vector_index_client/vector_index_client.py
> +from autointent.custom_types import LABEL_TYPE
Это константный тип. Я бы не стал менять

2024-11-01 14:36 UTC, truff4ut commented on autointent/context/context.py
> +        self.embedder_max_length = embedder_max_length
`embedder_max_length` + `embedder_batch_size`

2024-11-01 14:49 UTC, truff4ut commented on autointent/context/vector_index_client/vector_index_client.py
> +from autointent.custom_types import LABEL_TYPE
https://peps.python.org/pep-0008/#type-variable-names

2024-11-01 22:06 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +        if self.precomputed_embeddings:
а я как раз старался сделать интерфейс через VectorIndexClient, чтобы все модули могли обратиться к векторному индексу потому что это очень разделяемый ресурс

возможно просто стоит конкретно вот этот повторящийся код вынести в отдельную функцию или метод клиента векторного индекса

2024-11-01 22:09 UTC, voorhs commented on autointent/context/context.py
> +        self.embedder_max_length = embedder_max_length
да, это точно

в целом есть планах задачка упростить инициализацию контекста

2024-11-01 22:20 UTC, voorhs commented on autointent/context/vector_index_client/vector_index_client.py
> +            res = self.get_index(model_name)
я сейчас заметил что этот метод вообще нигде не используется, а используется связка методов `exists()` + `get_index()`

так что я просто удалю метод `get_or_create_index()`

2024-11-02 08:51 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +        if isinstance(labels[0], list):
@Samoed 

а как думаешь хорошая идея сделать pydantic-модель Label? это даст валидацию и поможет навесить функционал по проверке типа, но может есть какие-то подводные камни о которых я не подозреваю

2024-11-02 09:04 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +            vector_index_client = VectorIndexClient(self.device, self.db_dir, self.batch_size, self.max_length)
посмотрел с компа, да, было лишнее пересоздание клиента

2024-11-02 09:08 UTC, Samoed commented on autointent/modules/scoring/description/description.py
> +        if isinstance(labels[0], list):
Не надо пока. Мы все равно пока на датасеты переделывать будем

2024-11-05 07:21 UTC, voorhs commented
TODO:
- long `__init__` in Context 
- ugly `load` and `dump`
- option not to save module dumps and db dir

2024-11-05 07:21 UTC, merged