Feat/intent description
deeppavlov/AutoIntent pull request #28
Opened 2024-10-24 15:41 UTC by Darinochka

- Добавлен модуль autointent/generation/description_generation.py, основная функция enhance_dataset_with_descriptions, которая добавляет в каждый интент его описание.
- Добавлен DescriptionScorer, который сравнивает вектор utterances с вектором описания интентов.

2024-10-24 15:45 UTC, Samoed commented on autointent/generation/description_generation.py
> +    content = PROMPT_DESCRIPTION.format(intent_name=intent_name, user_utterances="\n".join(utterances[:5]))
Мб промпт вынести в аргументы функции?

2024-10-24 15:45 UTC, Samoed commented on autointent/generation/description_generation.py
> +    client = AsyncOpenAI(
Мб передавать сразу клиент, чтобы была возможность передачи доп парамеров, но нам не пришлось больше поддерживать

2024-10-24 17:19 UTC, Darinochka commented on autointent/generation/description_generation.py
> +    content = PROMPT_DESCRIPTION.format(intent_name=intent_name, user_utterances="\n".join(utterances[:5]))
передавать путь к .txt или к .py файлу? прсто он большой, как str передавать его не очень мне кажется. хотя не знаю

2024-10-24 17:24 UTC, Samoed commented on autointent/generation/description_generation.py
> +    content = PROMPT_DESCRIPTION.format(intent_name=intent_name, user_utterances="\n".join(utterances[:5]))
Просто в параметрах функции базовой 
```python
prompt: str =  PROMPT_DESCRIPTION
```

2024-10-24 17:26 UTC, Samoed commented on autointent/generation/description_generation.py
> +    dataset: Dataset, api_base: str, api_key: str, model_name: str = "gpt-3.5-turbo"
```suggestion
    dataset: Dataset, api_base: str, api_key: str, model_name: str = "gpt-4o-mini"
```
Она быстрее, лучше дешевле

2024-10-24 17:27 UTC, Darinochka commented on autointent/generation/description_generation.py
> +    client = AsyncOpenAI(
клиент может быть асинхронным и не асинхронным (AsyncOpenAI, OpenAI),  кажется другим он быть не может. от клиента зависит будет это async или нет в дальнейшем. можно сделать два варианта. аргументы можно передавать через *args, и **kwargs для доп параметров

вообще в будущем как будто хочется добавить еще оффлайн батчинг, так как генерация интент дескрипшнов не  в инференсе нам нужна, а в оптимизации. оффлайн батчинг медленнее (для небольших датасетов несильно медленнее), но дешевле раза в 2

2024-10-24 17:30 UTC, Samoed commented on autointent/generation/description_generation.py
> +    client = AsyncOpenAI(
Клиент можно и один оставить это не проблема. Можно просто тип проверить, а если он не верный кидать ошибку. Можно тогда добавить в функцию **client_params

2024-10-24 17:55 UTC, Darinochka commented on autointent/generation/description_generation.py
> +    content = PROMPT_DESCRIPTION.format(intent_name=intent_name, user_utterances="\n".join(utterances[:5]))
я поменяла, но единственное, я пока только в enhance_dataset_with_descriptions добавила проверку что промпт имеет {user_utterances} и {intent_name}. по хорошему наверное надо пайдантик модель сделать?

```
class PromptDescription(BaseModel):
    text: str = PROMPT_DESCRIPTIONS
    
    @validator('prompt_description')
    def check_valid_prompt(cls, value: str) -> str:
        if value.find("{intent_name}") == -1 or value.find("{user_utterances}") == -1:
            raise ValueError("The 'prompt_description' template must properly include {intent_name} and {user_utterances} placeholders.")
        return value
```

2024-10-24 17:56 UTC, Darinochka commented on autointent/generation/description_generation.py
> +    client = AsyncOpenAI(
так, пока не поняла, если передает клиента то нет надобности в **client_params же? или ты предлагаешь что-то из выбрать?

2024-10-24 17:58 UTC, Samoed commented on autointent/generation/description_generation.py
> +    client = AsyncOpenAI(
Да, выбери что-нибудь

2024-10-25 08:46 UTC, voorhs requested changes

2024-10-25 08:46 UTC, voorhs commented on autointent/generation/description_generation.py
> +def get_utternaces_by_id(utterances: list[Utterance]) -> dict[int, list[str]]:
очепятка в слове `utterances`

2024-10-25 08:46 UTC, voorhs commented on autointent/generation/description_generation.py
> +            intent_utterances[utterance.label].append(text)
у объекта типа `Utterance` есть метод `type`, возможно стоит использовать его чтобы код был более прозрачным

https://github.com/deeppavlov/AutoIntent/blob/feat/intent-description/autointent/context/data_handler/schemas.py#L35

2024-10-25 08:46 UTC, voorhs commented on autointent/generation/prompts.py
> +user want to know why his beneficiary is not allowed
present simple he/she/it `wants to` а не `want to` :)

2024-10-25 08:46 UTC, voorhs commented on autointent/modules/scoring/description/description.py
> +        return distances
выходом должны быть вероятности поэтому я предлагаю следующее:
- добавить в конструктор модуля параметр `temperature` с дефолтным значением `1.0`
- в случае multilabel классификации делать `return scipy.special.expit(distances / self.temperature)`
- в случае multiclass классификации делать `return scipy.special.softmax(distances / self.temperature, axis=1)`

2024-10-25 08:46 UTC, voorhs commented on experiments/intent_description/ac_robotic_new_with_intent_desc.json
> +            "description": "user wants information about a place"
опа, а это неправильно

2024-10-25 08:46 UTC, voorhs commented on experiments/intent_description/ac_robotic_new_with_intent_desc.json
> +            "description": "user wants to say something"
это тоже

2024-10-25 08:46 UTC, voorhs commented on experiments/intent_description/ac_robotic_new_with_intent_desc.json
> +            "description": "user wants to sit down."
и это неправильно...

2024-10-25 08:46 UTC, voorhs commented on experiments/intent_description/ac_robotic_new_with_intent_desc.json
> +            "description": "user wants to know about standing up"
и это

2024-10-25 08:46 UTC, voorhs commented on experiments/intent_description/ac_robotic_new_with_intent_desc.json
тут дескрипшены неправильные( видимо чатгпт затупил, это нам сигнал что надо промт переработать

2024-10-25 12:54 UTC, Darinochka commented on autointent/generation/description_generation.py
> +            intent_utterances[utterance.label].append(text)
mypy не позволяет использовать type, хочет явного сравнения

2024-10-28 13:58 UTC, voorhs reviewed
все ок

2024-10-28 14:33 UTC, voorhs approved these changes

2024-10-29 07:29 UTC, voorhs commented
я сегодня еще посмотрю про клиппинг и возможно добавлю пару тестов

2024-10-29 09:33 UTC, voorhs approved these changes

2024-10-29 10:07 UTC, merged