init docs
deeppavlov/AutoIntent pull request #45
Opened 2024-11-13 21:31 UTC by Samoed

2024-11-20 12:35 UTC, voorhs commented on Makefile
> +
вот это я уберу

2024-11-20 12:36 UTC, voorhs commented on .gitignore
> +docs/_build/
тут поправлю

2024-11-20 22:30 UTC, voorhs requested changes
я подредачу еще и сам смержу

в основном не хватает пояснений к модулям и еще хочется написать что-то поподробнее

2024-11-20 22:30 UTC, voorhs commented on autointent/context/embedder.py
>      batch_size: int
гугловский формат докстринга, надеюсь это не страшно) если что потом сконвертим

2024-11-20 22:30 UTC, voorhs commented on autointent/context/embedder.py
> +
тоже гугл

2024-11-20 22:30 UTC, voorhs commented on autointent/context/optimization_info/data_models.py
> +    """Artifact containing details from the retrieval node."""
здесь был информативный докстринг, стоит добавить инфу о том что за артифакты тут хранятся

2024-11-20 22:30 UTC, voorhs commented on autointent/context/optimization_info/data_models.py
> +    """Artifact containing outputs from the scoring node."""
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/context/optimization_info/data_models.py
> +    """Artifact containing outputs from the predictor node."""
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/context/optimization_info/data_models.py
> +    """Container for storing and managing artifacts generated by pipeline nodes."""
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/custom_types.py
> +"""
тут надо будет добавить побольше конкретики (что это связано с KNN и все такое)

2024-11-20 22:30 UTC, voorhs commented on autointent/custom_types.py
> +"""
тут надо будет расшифровать какие именно инты хранятся в списке (бинарные или любые положительные)

на самом деле это в библиотеке у нас смешивается, но я пока никак не знаю как разделить эти два случая на два разных тайп элиаса

2024-11-20 22:30 UTC, voorhs commented on autointent/custom_types.py
> +NodeTypeType = Literal["retrieval", "prediction", "scoring", "regexp"]
забавно выглядит)

2024-11-20 22:30 UTC, voorhs commented on autointent/metrics/prediction.py
>      y_true_, y_pred_ = transform(y_true, y_pred)
тут надо сохранить инфу о том что поддерживаются оба режима классификации

2024-11-20 22:30 UTC, voorhs commented on autointent/metrics/prediction.py
> +    """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/metrics/prediction.py
> +    """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/metrics/prediction.py
>      return f1_score(y_true, y_pred, average="macro")  # type: ignore[no-any-return]
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/metrics/retrieval.py
надо будет в докстрингах или гдето в туториалах объяснить разницу между `intersecting` и `macro`

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        """
строчки `:return:` наверное не должно быть?

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        :return:
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        :return:
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/base.py
> +        """
и тут

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/prediction/argmax.py
> +        """
не упомянуто что `raises WrongClassificationProblem`

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/prediction/argmax.py
> +        """
а тут `raises InvalidNumClassesError`

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/prediction/jinoos.py
> +
надо будет тут оставить ссылку на оригинальную статью

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/retrieval/vectordb.py
> +    """
ну вот это на самом деле не так) этот модуль используется только в оптимизации для подбора эмбедера

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
> +    train a logistic regression head on top of cross-encoder features.
DNNC = discriminative nearest neighbor classification

надо будет тоже оставить ссылку на ориг статью

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/scoring/dnnc/dnnc.py
> +        """
тут надо больше пояснений что такое rich output

2024-11-20 22:30 UTC, voorhs commented on autointent/modules/scoring/linear.py
> -    ```
терять эти TODO не хочется

2024-11-20 22:30 UTC, voorhs commented on docs/conf.py
этот файлик надо удалить перед мерджем

2024-11-20 22:30 UTC, voorhs commented on docs/index.rst
и этот

2024-11-20 22:30 UTC, voorhs commented on pyproject.toml
> -optional = true
группа должна быть опциональной

2024-11-20 22:39 UTC, Samoed commented on pyproject.toml
> -optional = true
Странно как-то сменилось. Оставлял опциональной

2024-11-21 10:08 UTC, Samoed commented on pyproject.toml
> -optional = true
Я ниже перенес просто

2024-11-21 10:26 UTC, Samoed commented on autointent/modules/prediction/jinoos.py
> +
Не смог найти

2024-11-21 10:29 UTC, Samoed commented
Что знаю, то поправил

2024-11-22 11:46 UTC, merged