Feat/sklearn scorer
deeppavlov/AutoIntent pull request #59
Opened 2024-11-29 10:15 UTC by JakeRaskind

2024-12-03 12:24 UTC, voorhs reviewed
тесты надо написать, а в целом ок

2024-12-03 12:24 UTC, voorhs commented on autointent/modules/scoring/_sklearn/scorer.py
> +        clf_args: dict[str, Any] = {},  # noqa: B006
лучше сделать `clf_args: dict[str, Any] | None = None`, а в конструкторе реализовать подстановку `{}` когда на вход получили `None`

2024-12-03 12:24 UTC, voorhs commented on autointent/modules/scoring/_sklearn/scorer.py
> +            # this happens only when LinearScorer is within Pipeline opimization after RetrievalNode optimization
комментарий надо обновить на `SklearnScorer`

2025-01-19 14:16 UTC, Samoed commented on autointent/_embedder.py
> +        :param model_name_or_path: Path to a local model directory or a Hugging Face model name.
FYI https://github.com/astral-sh/ruff/pull/13286, https://github.com/astral-sh/ruff/pull/14496

2025-01-20 12:33 UTC, voorhs requested changes

2025-01-20 12:33 UTC, voorhs commented on autointent/_embedder.py
> +        :param model_name_or_path: Path to a local model directory or a Hugging Face model name.
к чему эти ссылки?)

2025-01-20 12:33 UTC, voorhs commented on autointent/modules/scoring/_sklearn/sklearn_scorer.py
> +    db_dir: str
эти 4 атрибута не нужны, от них избавились в #93

2025-01-20 12:33 UTC, voorhs commented on autointent/modules/scoring/_sklearn/sklearn_scorer.py
> +    ) -> None:
к следующим аргументам конструктора и атрибуты класса лучше добавить префикс  `embedder_`:
- `device`
- `batch_size`
- `max_length`

2025-01-20 12:33 UTC, voorhs commented on autointent/modules/scoring/_sklearn/sklearn_scorer.py
> +    ) -> Self:
надо добавить аргументы `embedder_batch_size`, `embedder_max_length`, `embedder_device`

2025-01-20 12:33 UTC, voorhs commented on autointent/modules/scoring/_sklearn/sklearn_scorer.py
> +        """
от этого избавились в #93 , метод надо убрать

2025-01-20 12:33 UTC, voorhs commented on autointent/modules/scoring/_sklearn/sklearn_scorer.py
> +        """
от этого избавились в #93 , метод надо убрать

2025-01-20 12:47 UTC, Samoed commented on autointent/_embedder.py
> +        :param model_name_or_path: Path to a local model directory or a Hugging Face model name.
То что сейчас ruff не проверяет есть ли локументация к аргументам функции в формате sphinx

2025-01-20 13:22 UTC, voorhs commented on autointent/_embedder.py
> +        :param model_name_or_path: Path to a local model directory or a Hugging Face model name.
даа, это потом будем ближе к релизу отслеживать

а лучше бы конечно issue каждый раз открывать как видишь но так никто не будет делать, даже я)

2025-01-20 13:25 UTC, voorhs commented
только что понял что надо еще добавить sklearn scorer в `tests/nodes/test_scoring.py`, еще в `tests/configs/multiclass.yaml` и `tests/configs/multilabel.yaml`

2025-01-20 13:31 UTC, Samoed commented on autointent/_embedder.py
> +        :param model_name_or_path: Path to a local model directory or a Hugging Face model name.
https://github.com/deeppavlov/AutoIntent/issues/99

2025-01-21 18:49 UTC, voorhs approved these changes

2025-01-21 18:49 UTC, voorhs commented on autointent/modules/scoring/_sklearn/sklearn_scorer.py
> +        cv: int = 3,
Аргументы cv и n_jobs кажется не используются нигде

2025-01-21 20:27 UTC, merged