Feat/logreg retrieval
deeppavlov/AutoIntent pull request #81
Opened 2024-12-12 21:16 UTC by Darinochka

2024-12-12 21:48 UTC, Samoed commented on autointent/modules/embedding/_retrieval.py
> +            self.label_encoder = LabelEncoder()
Может лучше сделать через get params/set params?

2024-12-18 13:59 UTC, voorhs requested changes

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +    for classification tasks.
модуль для прокси подбора эмбедера

для предикта не используется

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +        self.vector_index = vector_index_client.create_index(self.embedder_name, utterances, labels)
сейчас у нас по другому работает получение эмбедингов, достаточно просто инициализировать эмбедер и  если включено кеширование и ранее эмбединги считались, то они подтянутся

для уточнения посмотри код для LinearScorer и/или спроси у Егора

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +        self.classifier.fit(embeddings, encoded_labels)
кажется не обрабатывается случай мультилейбл, посмотри LinearScorer как там работает

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +    ) -> float:
нужна не RetrievalMetricFn, а ScoringMetricFn

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +        return metric_fn(labels, [predicted_labels])
ну и тут скобки не нужны будут если скоринговые метрики использовать

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +        )
стоит использовать свой один TypedDict для хранения метадаты, не надо разбивать на два, тем более брать один из них из соседнего модуля

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +            json.dump(self.classifier_metadata, file, indent=4)
а классификатор sklearn лучше сохранять с помощью библиотеки joblib

2024-12-18 13:59 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +        return predicted_labels, predicted_probabilities, texts
обсуждали что предикт не нужен

2024-12-19 17:12 UTC, Darinochka commented on autointent/modules/embedding/_retrieval.py
> +        self.vector_index = vector_index_client.create_index(self.embedder_name, utterances, labels)
а VectorIndexClient в итоге тоже нужно инициализировать? просто без него KNN Scorer не хочет работать

2024-12-19 17:19 UTC, Darinochka commented on autointent/modules/embedding/_retrieval.py
> +        return predicted_labels, predicted_probabilities, texts
ABC модуль требует функцию predict, мне логику менять или как лучше сделать?

2024-12-19 17:35 UTC, Samoed commented on autointent/modules/embedding/_retrieval.py
> +        return predicted_labels, predicted_probabilities, texts
Наверное ошибку кидай или просто pass

2024-12-19 17:53 UTC, Darinochka commented on autointent/modules/embedding/_retrieval.py
> +        return predicted_labels, predicted_probabilities, texts
да сделала pass, получается  в RetrieverEmbedder аналогично сделать?

2024-12-19 18:15 UTC, Samoed commented on autointent/modules/embedding/_retrieval.py
> +        return predicted_labels, predicted_probabilities, texts
Да, можно так

2024-12-22 07:30 UTC, voorhs commented
closes #79

2024-12-22 07:30 UTC, voorhs commented
closes #44

2024-12-22 07:45 UTC, Samoed commented
Closes надо в описании pr писать, чтобы автоматически все закрывалось.

2025-01-17 12:31 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> +        return self.score_metrics(([labels], [predicted_labels]), metrics_dict)
здесь должно быть `predict_proba`

2025-01-17 12:39 UTC, voorhs commented
сейчас проблема что никак объективно нельзя сравнить LogregEmbedding и RetrievalEmbedding по какой-то прокси-метрике, поэтому будем ограничивать пользователя: в search space разрешим указывать только что-то одно

в будущем надо добавить автоконфигурацию пайплайна не с помощью жадной оптимизиации по прокси-метрикам, а с помощью оценки всего пайплайна; вот тогда эта фича с разными прокси-подобранными эмбедингами заиграет красками

2025-01-20 11:48 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
>          predicted_encoded = self.classifier.predict(embeddings)
здесь надо `predict_proba`

2025-01-20 11:48 UTC, voorhs commented on autointent/modules/embedding/_retrieval.py
> -        return self.score_metrics(([labels], [predicted_labels]), metrics_dict)
и тогда тут будут работать `SCORING_METRICS`

2025-01-22 08:30 UTC, Darinochka commented
https://wandb.ai/darinka/autointent/workspace?nw=nwuserdarinka - эксперименты по сравнению logreg | retrieval для некоторых датасетов

2025-01-22 09:42 UTC, Samoed commented
Пофикси конфликт с main

2025-01-22 09:45 UTC, Samoed commented on autointent/modules/embedding/_logreg.py
> +    def dump(self, path: Path) -> None:
Dump и load убрали

2025-01-22 09:46 UTC, Samoed commented on autointent/modules/embedding/_logreg.py
> +    classes: list[str]
Это тоже тогда можно будет удалить

2025-01-22 09:47 UTC, Samoed commented
Добавь модуль в `tests/assets/configs/multiclass.yaml` и `tests/nodes/test_scoring.py`

2025-01-22 10:25 UTC, voorhs requested changes
Все ок. Осталось добавить в `tests/nodes` и `tests/assets/configs`. В первом случае надо написать аналог файла `test_retrieval.py` только `test_logreg.py`. Во втором случае предлагаю в `multilabel.yaml` заменить `module_type: retrieval` на `module_type: logreg`, а `multiclass.yaml` оставить прежним

2025-01-22 10:25 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +    label_encoder: LabelEncoder
эти два атрибута приватные, назови их `_classifier` и `_label_encoder`

2025-01-22 10:26 UTC, voorhs commented
> Добавь модуль в `tests/assets/configs/multiclass.yaml` и `tests/nodes/test_scoring.py`

это embedding нода, а не scoring; выше в своем ревью написал как лучше сделать

2025-01-27 09:17 UTC, voorhs reviewed
в будущем думаю надо еще подумать над названиями, потому что `RetrievalEmbedding` и `LogRegEmbedding` мне перестали нравиться

сейчас мне больше всего нравится идея назвать их `RetrievalAimedEmbedding` и `ClassificationAimedEmbedding`

2025-01-27 09:17 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +    for classification tasks.
я потом перед мерджем поправлю описание

2025-01-27 09:17 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +        self._embedder = Embedder(
здесь в начало метода стоит добавить валидацию входов как я это сделал например [тут](https://github.com/deeppavlov/AutoIntent/blob/dev/autointent/modules/scoring/_knn/knn.py#L135)

вообще мне стоит сделать отдельный пр и добавить эту валидацию либо во все классы либо в базовый класс каким-то образом

2025-01-27 09:17 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +    _label_encoder: LabelEncoder
надо исправить аннотацию типа на `LabelEncoder | None`

2025-01-27 09:17 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +            probas = np.stack(probas, axis=1)[..., 1]
я бы вынес эти строки в метод `predict`

2025-01-27 09:17 UTC, voorhs commented on tests/modules/retrieval/test_logreg.py
> +    mock_context.data_handler.test_labels.return_value = [[1, 0], [0, 1]]
выглядит странно в `fit` ты подавала мультикласс метки, а не тесте даешь мультилейбл

2025-01-27 10:53 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +        self._embedder = Embedder(
после мерджа #105 поправлю сам этот момент

2025-01-27 10:54 UTC, voorhs commented on autointent/modules/embedding/_logreg.py
> +    _label_encoder: LabelEncoder
а еще `LogisticRegressionCV | MultiOutputClassifier`

2025-01-27 11:01 UTC, Samoed commented on tests/modules/retrieval/test_logreg.py
> +    mock_context.data_handler.test_labels.return_value = [[1, 0], [0, 1]]
Мы до этого не использовали моки, думаю сейчас не надо их добавлять

2025-01-27 18:12 UTC, Darinochka commented on tests/modules/retrieval/test_logreg.py
> +    mock_context.data_handler.test_labels.return_value = [[1, 0], [0, 1]]
я заменила на тест predict, так как score в целом оценивается в другом модуле

2025-01-27 18:12 UTC, Darinochka commented on autointent/modules/embedding/_logreg.py
> +            probas = np.stack(probas, axis=1)[..., 1]
done

2025-01-27 18:12 UTC, Darinochka commented on autointent/modules/embedding/_logreg.py
> +    _label_encoder: LabelEncoder
done

2025-01-27 20:46 UTC, voorhs approved these changes
супер, ща подтяну dev и сам вмерджу

2025-01-28 06:23 UTC, merged